apiVersion: v1
kind: Service
metadata:
  name: day304-api
  namespace: day304
  labels:
    app: day304-api
spec:
  selector:
    app: day304-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
